[versions]
#AGP
agp = "7.1.1"
#Gradle
gradle = "7.3.3"
#Kotlin
kotlin = "1.6.21"
#Android Config
compileSdk = "32"
minSdk = "23"
targetSdk = "32"
#Coroutines
coroutines = "1.6.1"
#Legacy support
legacySupport = "1.0.0"
#UI Components
material = "1.5.0"
constraint = "2.1.3"
viewBindingPropertyDelegate = "1.5.6"
appCompat = "1.4.1"
splashScreen = "1.0.0-beta01"
maskedEditText = "1.0.4"
#Core
core = "1.7.0"
#Activity
activity = "1.4.0"
#fragment
fragment = "1.4.1"
#Lifecycle
lifecycle = "2.4.1"
#Navigation
navigation = "2.4.1"
#Hilt
hilt = "2.42"
hiltNavGraphViewModels = "1.0.0"
#Javax
javax = "1"
#Retrofit
retrofit = "2.9.0"
#OkHttp
okHttp = "5.0.0-alpha.5"
#Room
room = "2.4.2"
#Datastore
datastore = "1.0.0"
#Paging
paging = "3.1.1"
#Firebase
firebaseFirestore = "24.1.2"
googleServices = "4.3.10"
firebasePlatform = "30.0.1"
firebaseCrashlytics = "2.8.1"
firebaseCoroutines = "1.6.1"
#Glide
glide = "4.13.0"
#Koin
koin = "3.2.0-beta-1"
[libraries]

#Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

#Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

#Core
android-core = { module = "androidx.core:core-ktx", version.ref = "core" }

#UI Components
ui-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
ui-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
ui-material = { module = "com.google.android.material:material", version.ref = "material" }
ui-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
ui-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
ui-viewBindingPropertyDelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version.ref = "viewBindingPropertyDelegate" }
ui-splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
ui-maskedEditText = { module = "com.github.pinball83:masked-edittext", version.ref = "maskedEditText" }
glide-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

#Legacy Support
legacySupport-legacySupport = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupport" }

#Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-liveData = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

#Navigation
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-viewModels = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavGraphViewModels" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

#Javax
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax" }

#Retrofit
retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gsonConverter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

#OkHttp
okHttp-okHttp = { module = "com.squareup.okhttp3:okhttp" }
okHttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttp" }
okHttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

#Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-kotlinExtensionsAndCoroutinesSupport = { module = "androidx.room:room-ktx", version.ref = "room" }

#Preferences and Datastore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-proto = { module = "androidx.datastore:datastore", version.ref = "datastore" }

#Paging
paging-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

#Firebase
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestore" }
firebase-platform = { module = "com.google.firebase:firebase-bom", version.ref = "firebasePlatform" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "firebaseCoroutines" }
#Koin
koin-koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }

[bundles]
#UI Components
uiComponents = ["ui-activity", "ui-fragment", "ui-appCompat", "ui-constraint", "ui-material", "ui-viewBindingPropertyDelegate", "glide-glide", "ui-splashScreen", "ui-maskedEditText"]

#Room
room = ["room-runtime", "room-kotlinExtensionsAndCoroutinesSupport"]

#Datastore
datastore = ["datastore-preferences", "datastore-proto"]

#Retrofit
retrofit = ["retrofit-retrofit", "retrofit-gsonConverter"]

#Hilt

hilt = ["hilt-android", "hilt-viewModels"]

#OkHttp
okHttp = ["okHttp-bom", "okHttp-loggingInterceptor", "okHttp-okHttp"]

#Navigation
navigation = ["navigation-fragment", "navigation-ui"]

#Lifecycle
lifecycle = ["lifecycle-viewModel", "lifecycle-runtime", "lifecycle-liveData"]

#Firebase
firebase = ["firebase-firestore", "firebase-platform", "firebase-coroutines"]
firebaseNoCrashlytics = ["firebase-firestore", "firebase-coroutines", "firebase-analytics", "firebase-auth"]


[plugins]
#AGP

agp-application = { id = "com.android.application", version.ref = "agp" }
agp-library = { id = "com.android.library", version.ref = "agp" }

#Kotlin
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#Navigation
navigation-safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

#Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

#Google Services
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

#Firebase
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }